holland-backup/holland

docs/source/provider_plugins/mysqldump.rst

It now includes mention of what the filename is called when setting
file-per-database to know.

Updated file-per-database explanation [Issue 117]

---

plugins/holland.backup.xtrabackup/setup.py

Typo from a previous update that was causing a syntax error.

Add missing comma in xtrabackup plugin's setup.py

---

holland/commands/backup.py

https://github.com/holland-backup/holland/issues/121
[after|before|failed]-backup-command is executed during a dry run

Don't run hooks during dry run

---

plugins/holland.lib.mysql/holland/lib/mysql/schema/base.py

Fixes a bug where MariaDB 10.1 seems to be defaulting to decimal
when transforming certain integer types with coalesce/ifnull/etc.
Resolves #125

Ensure data_length / index_length are integers

---

docs/source/config.rst

Added documentation for the [holland:backup] purge-on-demand
option, that purges previous backups to make space for a new
backup when possible.
Resolves #130

add documentation for purge-on-demand option

---

CHANGES.rst

This adds four notes to the changelog for:
- Issue #125 (mysqldump estimation failures under MariaDB 10.1)
- Issue #121 (hook commands are no longer run under --dry-run)
- Issue #116 (pgdump now escapes passwords for PGPASSFILE)
- PR #95 (gpg added as a compression target)

add a few missing entries to CHANGES.rst

---

contrib/holland.spec
plugins/holland.backup.example/setup.py
plugins/holland.backup.mysql_lvm/setup.py
plugins/holland.backup.mysqldump/setup.py
plugins/holland.backup.mysqlhotcopy/setup.py
plugins/holland.backup.pgdump/setup.py
plugins/holland.backup.random/setup.py
plugins/holland.backup.sqlite/setup.py
plugins/holland.backup.tar/setup.py
plugins/holland.backup.xtrabackup/setup.py
plugins/holland.lib.common/setup.py
plugins/holland.lib.lvm/setup.py
plugins/holland.lib.mysql/setup.py
setup.py

This bumps the version numbers of all packages of core setup.py and plugins/*/setup.py 1.0.12 as well as the holland.spec.  Minor date discrepancies in holland.spec reported by rpmlint were fixed as well.

Bump master version to 1.0.12

---

config/providers/tar.conf
contrib/holland.spec
plugins/holland.backup.tar/LICENSE
plugins/holland.backup.tar/README
plugins/holland.backup.tar/holland/backup/tar.py

- add missing providers/tar.conf - this is expected by holland.spec
- convert tabs to spaces
- cleanup unused imports
- fail if tar exits with non-zero status
- disable building tar plugin by default
(due to requiring python2.6+)

minor fixes for tar plugins

---

plugins/holland.lib.mysql/holland/lib/mysql/client/base.py

This was previously changed as part of a fix for invalid
view detection in MySQL 5.0, where views were never being
detected correctly in order for the invalid view filtering
to work.  Unfortunately this introduced mutating the row
dictionary while iterating over the raw dictionary directly
which results in a "dictionary changed size during iteration"
error.  keys() are not iterated over to avoid that situation.

fix bad iteration over rows in mysql50 metadata discovery

---

contrib/holland.spec

contrib/holland.spec had an ancient dependency on
"xtrabackup >= 1.2", but for any remotely recent xtrabackup
this should be "percona-xtrabackup".

Fix holland-xtrabackup percona-xtrabackup dependency

---

plugins/holland.backup.xtrabackup/holland/backup/xtrabackup/plugin.py

For some reason the Percona XtraBackup plugin explicitly skipped
compressing xbstream.
Fixes LP#1246562

Allow the plugin for Percona XtraBackup to support compressed xbstream

---

CHANGES.rst
plugins/holland.lib.mysql/holland/lib/mysql/client/base.py

The fix for LP#1220841 breaks show_slave_status() in the holland mysql client ``show_slave_status()`` method.  ``binary`` is not a valid character set for MySQLdb. This leads to an 'unknown encoding' error and the backup fails.
Without changing connectors to something other than MySQLdb - where 'raw' binary strings can be had easily - I think [LP#1220841](https://bugs.launchpad.net/holland-backup/+bug/1220841)  is not easily fixed. The original fix for this show slave status bug is reverted here to address the serious defect it introduced in holland 1.0.12.

Revert broken SHOW SLAVE STATUS fix for LP#1220841

---

CHANGES.rst
plugins/holland.lib.mysql/holland/lib/mysql/client/base.py

There was a regression from the fix for LP#1081261 which caused
storage engine name comparison to be done in lowercase. The engine
attribute was canonicalized in the path for INFORMATION_SCHEMA
(MySQL 5.1+), but not for the "SHOW TABLE STATUS" path (used for
MySQL 5.0 and earlier). This causes the mysqldump option
lock-method=auto-detect to always default to 'non-transactional'
for MySQL 5.0 envionments and use the default mysqldump option
--lock-tables.
Resolves #148

Fix lock-method = auto-detect for MySQL 5.0

---

plugins/holland.backup.xtrabackup/holland/backup/xtrabackup/plugin.py

Workaround for versions of Percona XtraBackup before 2.2.6:
https://bugs.launchpad.net/percona-xtrabackup/+bug/1343722
Currently, specification of socket in .my.cnf via defaults-extra-file can result in a silent failure (wrong data) for old versions of Percona XtraBackup
The proposed change includes [mysql:client] defaults-extra-file first, so that values in [xtrabackup] global-defaults win

Reorder !include in generated my.cnf

---

plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py

Error occurs in case there's a Illegal mix of collations.
----------------------------
perror 1271
MySQL error code 1271 (ER_CANT_AGGREGATE_NCOLLATIONS): Illegal mix of collations for operation '%s'
----------------------------

Added code to allowed invalid views codes if exclusion is set to yes.

---

docs/source/conf.py
docs/source/config.rst
docs/source/index.rst
docs/source/intro.rst
docs/source/overview.rst
docs/source/provider_plugins/compression.rst
docs/source/provider_plugins/databasefiltering.rst
docs/source/provider_plugins/example.rst
docs/source/provider_plugins/mysql-lvm.rst
docs/source/provider_plugins/mysqlconfig.rst
docs/source/provider_plugins/mysqldump-lvm.rst
docs/source/provider_plugins/mysqldump.rst
docs/source/provider_plugins/pgdump.rst
docs/source/provider_plugins/xtrabackup.rst
docs/source/providers.rst

Here's the original documentation updates I made, without the rsync plugin. Admittedly I haven't gone through them in depth other than making sure they built and had some of the changes I knew I made. Should be the same as the original PR (again minus the rsync stuff which I'll deal with later, per the list discussion).

Documentation Updates (w/o rsync plugin)

---

plugins/holland.backup.xtrabackup/holland/backup/xtrabackup/plugin.py

Reverts holland-backup/holland#151
Reading the server my.cnf after client .cnf options means `[mysqld]`'s user option is prioritized over whatever `[client]`/`[xtrabackup]` user option(s) might be specified in `~/.my.cnf` or elsewhere in the server my.cnf.  When innobackup connects it will often use the server's "user" option (almost always 'mysql') which leads to an auth failure / backup failure.  Percona XtraBackup using mysqld --user as a client option is an open bug.
Reverting this for now as I think the current plugin behavior with this change is not right and not so much of an issue for modern versions of Percona XtraBackup.

Revert "Reorder !include in generated my.cnf"

---

plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py

Log recorded/found relay_master_log_file/exec_master_log_pos and mimic master status sanity check
Currently:
2017-02-13 23:09:43,502 [WARNING] ALERT! Slave position changed during backup
PR Sample:
2017-02-13 23:09:43,502 [WARNING] Sanity check on slave status failed.  Previously recorded bin-log.000053:2951 but currently found bin-log.000055:120
2017-02-13 23:09:43,502 [WARNING] ALERT! Slave position changed during backup!

Clean up logging for slave status sanity  check

---

plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py

Minor correction on my previous PR which did not exactly mimic master status sanity check since I used %d instead of %s

Don't cast exec_master_log_pos to digit

---

plugins/holland.lib.mysql/holland/lib/mysql/client/base.py

Currently, it is not obvious that a delay can be caused by "STOP SLAVE" waiting on a query or rollback.
Before proposed change:
2017-02-13 21:30:37,541 [INFO] Holland 1.0.14 started with pid 24174
2017-02-13 21:30:37,552 [INFO] --- Starting backup run ---
2017-02-13 21:30:37,556 [INFO] Creating backup path /var/spool/holland/mysqldump_stop_slave/20170213_213037
2017-02-13 21:30:37,583 [INFO] Estimating size of mysqldump backup
2017-02-13 21:30:37,596 [INFO] Estimated Backup Size: 800.49KB
2017-02-13 21:30:37,596 [INFO] Starting backup[mysqldump_stop_slave/20170213_213037] via plugin mysqldump
2017-02-13 21:30:59,701 [INFO] Stopped slave
2017-02-13 21:30:59,702 [INFO] MySQL Replication has been stopped.
2017-02-13 21:30:59,703 [INFO] Using mysqldump executable: /usr/bin/mysqldump …

Log timestamp of issuing "STOP SLAVE"

---

holland/core/backup/base.py
holland/core/util/fmt.py
plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py

In certain circumstances connecting to remote DBaaS instances (Rackspace Cloud DB, MariaDB 10.1, Holland running on Ubuntu 14.04), the size checks/estimates (disk space, backup size estimate, backup size estimate adjustment, bytes format) are then a mix of Decimal and floats values which produce decimal/float errors when performing arithmetic. 
Resulting in the following errors:
```
Uncaught exception while running command 'bk': TypeError("unsupported operand type(s) for *: 'Decimal' and 'float'",)
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/holland/core/command/command.py", line 209, in dispatch
return self.run(self.optparser.prog, opts, *args)
File "/usr/lib/python2.7/dist-packages/holland/commands/backup.py", line 102, in run
runner.backup(name, config, …
```

Mysql float/decimal cast patch 1

---

setup.py

Holland makes heavy use of the pkg_resources module, which is part of setuptools.

add setuptools requirement

---

plugins/holland.lib.mysql/holland/lib/mysql/client/base.py

Original code called MySQLClient.__init__(), which calls MySQLdb.connect()
to immediately open connection and does nothing else. Problem is that
__init__() is called without args/kwargs, which results connection with
no username or password. That fails if "root" user requires password,
making plugin to fail.
Removing this super(...).__init__() fixed mysqldump-plugin for me. You know the code better, does it break something else? It should not. Another option is to change this line to super(...).__init__(*args, **kwargs), but then connection is not deferred.

mysql/PassiveMySQLClient: really defer mysql connection until connect()

---

plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/actions/mysql/_mysqld.py
plugins/holland.lib.common/holland/lib/which.py

The last version of 'which' wasn't strict enough. It would match `mysqld` and `mysqld_safe`.  This is looking for an exact match. Also discovered that mysql-lvm plugin was passing two arguments into the which function.

Fix error caused by rewriting the which command

---

plugins/holland.backup.mysqldump/holland/backup/mysqldump/base.py
plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py

Add new option that allows user's to specify mysqldump arguments per database, when `file-per-database` is true
> \#arg-per-database is only used if file-per-database is true
> \#\# takes a json object {"table1": "--arg", "table2": "--arg"}
> arg-per-database = {"employee1": "--no-data"}
Fixes #180

add arg_per_database. 

---

plugins/holland.backup.mysqldump/holland/backup/mysqldump/command.py

Support all --skip options. Ref document:
https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#mysqldump-option-summary

Support all --skip options. Closes #248.

---

.travis.yml
scripts/travis_ci.sh

Move pylint checks to travis_ci.sh. Let all pylint plugin checks run,
but if any fail, the script exits with failure status.

Move pylint checks to travis_ci.sh. Fixes #255.

---

contrib/holland-commvault/holland_commvault/__init__.py
contrib/holland-commvault/holland_commvault/commvault.py
contrib/holland-commvault/setup.py
scripts/travis_ci.sh

- Lint files
- Add holland_commvault module to pylint list in Travis CI
- Add logic so the commvault wrapper will wait for another instance of the wrapper to complete, and then return the other processes return code. This uses the commvault 'job' id, which is expected to be different for distant runs and backup sets.
(requires pid module)

Rework holland commvault wrapper

---

config/providers/mongodump.conf
plugins/holland.backup.mongodump/holland/backup/mongodump.py

Current "host/username/password" options are fine for single MongoDB
node setup. MongoDB cluster with replication needs more fine tuned
setup, for example:
uri = mongodb://user:pass@host1,host2,host3?replicaSet=setname&readPreference=primaryPreferred
With this change you can still use "host/username/password" as
previously, or replace them all with single "uri" parameter. If both
are defined, then "uri" will be used.

mongodump: add support for "uri" config option

---

config/providers/pg_basebackup.conf
plugins/holland.backup.pg_basebackup/holland/backup/pg_basebackup/base.py
plugins/holland.backup.pg_basebackup/holland/backup/pg_basebackup/interface.py

Remove role argument from pg_basebackup plugin

Remove role option that doesn't exist in pg_basebackup

---

plugins/holland.backup.mongodump/holland/backup/mongodump.py
plugins/holland.backup.mongodump/setup.py

PyMongo version 3.6 adds list_database_names() and version 4.0 removes database_names().

mongodump: fix compatibility with latest PyMongo

---

holland/commands/__init__.py

Relates to https://github.com/holland-backup/holland/issues/362
Removal of `pkg_resources` will require us to refactor the plugin loading a bit and will be pushed to the next major version update to holland. In the short-term we've elected to silence the deprecation warning as there is a desire to tag a new release soon.
@mikegriffin Not sure if you have cycles to test this - but I believe this should be sufficient.

Silence pkg_resources deprecation warning

---

plugins/holland.backup.xtrabackup/holland/backup/xtrabackup/util.py

Fix for #359 
When using percona-xtrabackup-24 (innobackupex is symlink to xtrabackup), also args.extend(extra_opts)

Fix for #359

---

plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py

Fixes https://github.com/holland-backup/holland/issues/382.
Initially I was going to allow it to accept Bb as a suffix but it seems more consistent to just interpret no suffix as correlating to bytes instead.

Allow values without a suffix to be interpreted as bytes

---

Jenkinsfile

Currently jenkins builds are failing due to how we currently install holland with setup.py. 
This is just a temporary workaround that installs pymongo via pip upfront in our Jenkinsfile to try and avoid encountering this issue.

Install pymongo upfront to avoid issue with pymongo installing via setup.py

---

plugins/holland.backup.mariabackup/holland/backup/mariabackup/plugin.py
plugins/holland.backup.mariabackup/holland/backup/mariabackup/util.py
plugins/holland.backup.xtrabackup/holland/backup/xtrabackup/plugin.py
plugins/holland.backup.xtrabackup/holland/backup/xtrabackup/util.py

Fixes #372.
Changes:
- Defaults the xtrabckup stream to xbstream when using mk-config
- In holland-xtrabackup - when using `stream=yes` and using xtrabackup > 8.0 - backup files would be written as `backup.tar.<compressor>` even though xbstream is being forced. The `determine_stream_method` has been updated to account for this and properly returns `xbstream` in this scenario. This should result in the proper filenames being written.
- In holland-mariabackup - the `open_mb_stdout` had a branch section that suggested `tar` was a valid stream option. This branch was removed as `determine_stream_method` only allows for `mbstream/xbstream` as config options.
- In holland-mariabackup - mariabackup has been symlinked to `mariadb-backup` in versions 10.4 and greater and generates a warning when …

Fix output filename for xtrabackup > 8.0 when using stream=yes and use preferred mariadb-backup binary

---

INSTALL.md
Jenkinsfile
config/providers/mariadb-dump.conf
holland/core/spool.py
plugins/holland.backup.mariadb_dump/GPL
plugins/holland.backup.mariadb_dump/LICENSE
plugins/holland.backup.mariadb_dump/README
plugins/holland.backup.mariadb_dump/holland/__init__.py
plugins/holland.backup.mariadb_dump/holland/backup/__init__.py
plugins/holland.backup.mariadb_dump/holland/backup/mariadb_dump/__init__.py
plugins/holland.backup.mariadb_dump/holland/backup/mariadb_dump/base.py
plugins/holland.backup.mariadb_dump/holland/backup/mariadb_dump/command.py
plugins/holland.backup.mariadb_dump/holland/backup/mariadb_dump/mock/__init__.py
plugins/holland.backup.mariadb_dump/holland/backup/mariadb_dump/plugin.py
plugins/holland.backup.mariadb_dump/setup.cfg
plugins/holland.backup.mariadb_dump/setup.py
plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py
plugins/holland.lib.common/holland/lib/util.py
plugins/holland.lib.mysql/holland/lib/mysql/util.py

Adds a new mariadb-dump plugin to facilitate the diversion of mariabd-dump from mysqldump occurring upstream. This started off largely as a copy and paste of the mysqldump plugin and some search and replace fun. It does have some diversions from mysqldump that I'm open to changing.
Changes from mysqldump:
- The backupset provider conf for this plugin includes all options we expose via the configspec.
- The configspec for mariadb-dump uses a generic `executable` setting that defaults to `mariadb-dump` and uses a new `get_cmd_path` method helper that ensure we properly search the holland defined environment PATH. This value can also be set to an absolute path. This also allows for the executable to be named anything so that a user could potentially even wrap the mariadb-dump call if needed …

Add new holland mariadb-dump plugin and various bug fixes

---

Jenkinsfile
config/providers/mysqlsh-dump-instance.conf
config/providers/mysqlsh-dump-schemas.conf
contrib/holland-commvault/setup.py
plugins/holland.backup.command/setup.py
plugins/holland.backup.example/setup.py
plugins/holland.backup.mariabackup/setup.py
plugins/holland.backup.mariadb_dump/setup.py
plugins/holland.backup.mongodump/setup.py
plugins/holland.backup.mysql_lvm/setup.py
plugins/holland.backup.mysqldump/setup.py
plugins/holland.backup.mysqlsh/setup.py
plugins/holland.backup.pg_basebackup/setup.py
plugins/holland.backup.pgdump/setup.py
plugins/holland.backup.random/setup.py
plugins/holland.backup.sqlite/setup.py
plugins/holland.backup.tar/setup.py
plugins/holland.backup.xtrabackup/setup.py
plugins/holland.lib.common/setup.py
plugins/holland.lib.lvm/setup.py
plugins/holland.lib.mysql/setup.py
setup.py

- Bumps version to 1.3.0 for next release.
- Bumps docs submodule to latest for 1.3.0 release
- Fixes a few small typos I found in the new mysqlsh provider configs.
- Adds a `--skip-os-eol-checks` to mariadb repo setup which was causing the jenkins job to fail.

Bump Holland version to 1.3.0
