holland-backup/holland

- docs/man/holland.1
Adding --dry-run into the man pages as its missing.
> dry run in the Man pages

- LICENSE
- holland/core/cmdshell.py
- plugins/holland.backup.example/GPL
- plugins/holland.backup.example/LICENSE
- plugins/holland.backup.mysql_lvm/GPL
- plugins/holland.backup.mysql_lvm/LICENSE
- plugins/holland.backup.mysqldump/LICENSE
- plugins/holland.backup.pgdump/LICENSE
- plugins/holland.backup.random/LICENSE
- plugins/holland.backup.sqlite/LICENSE
- plugins/holland.backup.xtrabackup/GPL
- plugins/holland.backup.xtrabackup/LICENSE
- plugins/holland.lib.common/GPL
- plugins/holland.lib.common/LICENSE
- plugins/holland.lib.lvm/GPL
- plugins/holland.lib.lvm/LICENSE
- plugins/holland.lib.mysql/GPL
- plugins/holland.lib.mysql/LICENSE
Just bumping the copyright year to 2016 in the relevant files.
> bump copyright to current year

- INSTALL
There are few file paths that needed to updated.  The only one I was unsure about was the 'Install Holland Core' section.  Should that use the setup.py within holland-x.y.z folder?  Let me know, and I will update my pull request.
-Ben
> correct file paths in INSTALL

- contrib/holland-commvault/setup.py
- contrib/holland.spec
- plugins/holland.backup.example/setup.py
- plugins/holland.backup.mysql_lvm/setup.py
- plugins/holland.backup.mysqldump/setup.py
- plugins/holland.backup.mysqlhotcopy/setup.py
- plugins/holland.backup.pgdump/setup.py
- plugins/holland.backup.random/setup.py
- plugins/holland.backup.sqlite/setup.py
- plugins/holland.backup.tar/setup.py
- plugins/holland.backup.xtrabackup/setup.py
- plugins/holland.lib.common/setup.py
- plugins/holland.lib.lvm/setup.py
- plugins/holland.lib.mysql/setup.py
- setup.py
Preparing for v1.0.14 release to address critical bug in holland v1.0.12.
> Bump holland version to 1.0.14

- tomsay.py
Its 2016, time to remove the smoke from tomsay and clean up the code
with pep8. Also support python 2 and 3.
> tomsay: Style cleanups

- contrib/holland-commvault/holland_commvault/commvault.py
- holland/core/cmdshell.py
- holland/legacy/config.py
Tested on FreeBSD 11 without issue when making and installing from a package.
This should resolve #169
> Adjust config path for FreeBSD compatibility

- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/common.py
> prevent logging of db credentials

- contrib/holland-commvault/setup.py
- plugins/holland.backup.example/setup.py
- plugins/holland.backup.mariabackup/setup.py
- plugins/holland.backup.mongodump/setup.py
- plugins/holland.backup.mysql_lvm/setup.py
- plugins/holland.backup.mysqldump/setup.py
- plugins/holland.backup.pgdump/setup.py
- plugins/holland.backup.random/setup.py
- plugins/holland.backup.sqlite/setup.py
- plugins/holland.backup.tar/setup.py
- plugins/holland.backup.xtrabackup/setup.py
- plugins/holland.lib.common/holland/lib/compression.py
- plugins/holland.lib.common/setup.py
- plugins/holland.lib.lvm/setup.py
- plugins/holland.lib.mysql/setup.py
- setup.py
Fix bug preventing [compression] options from being used correctly.
> Compression option bug

- .travis.yml
- README
- scripts/travis_ci.sh
Add travis-ci test for xtrabackup plugin
> Travis xtrabackups

- plugins/holland.backup.mariabackup/holland/backup/mariabackup/plugin.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/raw/plugin.py
- plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py
- plugins/holland.backup.pgdump/holland/backup/pgdump/interface.py
- plugins/holland.backup.xtrabackup/holland/backup/xtrabackup/plugin.py
- plugins/holland.lib.common/holland/lib/compression.py
Add zstd to all plugins, add missing lzma to mysql_lvm raw plugin, correct minor whitespace/quote issues
> add zstd compressor, minor fixes

- plugins/holland.backup.mysqldump/holland/backup/mysqldump/base.py
- plugins/holland.backup.pgdump/holland/backup/pgdump/base.py
- plugins/holland.lib.common/holland/lib/safefilename.py
> Create new encode function to replace safefilename

- plugins/holland.backup.mariabackup/holland/backup/mariabackup/plugin.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/raw/plugin.py
- plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py
- plugins/holland.backup.xtrabackup/holland/backup/xtrabackup/plugin.py
- plugins/holland.lib.mysql/holland/lib/mysql/client/base.py
move mysql client configuration to holland.lib.mysql
> Consolidate MySQL Client config to holland.lib.mysql

- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/common.py
- plugins/holland.lib.lvm/holland/lib/lvm/base.py
- plugins/holland.lib.lvm/holland/lib/lvm/raw.py
- plugins/holland.lib.lvm/holland/lib/lvm/snapshot.py
Improve error handling for LVM Snapshots and fix encoding issue for `lvs` command
> Fixes #224 and improve error handling

- .travis.yml
- plugins/holland.backup.pgdump/setup.py
- scripts/travis_ci.sh
> Add travis test

- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/actions/mysql/mysqldump.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/mysqldump/plugin.py
Set mysqld error log location to help debug mysqld issue when using the mysqldump_lvm plugin
> Allow users to set the error log location for mysqldump_lvm

- holland/core/backup/base.py
Remove raise statement that was preventing holland from correctly cleaning up failed backups
> Bug prevenint holland from pruing failed backups

- .pylintrc
- plugins/holland.backup.mysql_lvm/holland/__init__.py
- plugins/holland.backup.mysql_lvm/holland/backup/__init__.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/__init__.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/actions/__init__.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/actions/dir.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/actions/mysql/__init__.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/actions/mysql/_mysqld.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/actions/mysql/innodb.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/actions/mysql/lock.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/actions/mysql/mysqldump.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/actions/mysql/replication.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/actions/tar.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/__init__.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/common.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/innodb.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/mysqldump/__init__.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/mysqldump/plugin.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/mysqldump/util.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/raw/__init__.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/raw/plugin.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/raw/util.py
- plugins/holland.lib.lvm/holland/lib/lvm/base.py
- plugins/holland.lib.lvm/holland/lib/lvm/snapshot.py
Make sure mysql can write to the new log file and that it gets copied to spool directory after the backup is complete.
> Improve on #241

- CHANGES.rst
- contrib/holland-commvault/setup.py
- plugins/holland.backup.example/setup.py
- plugins/holland.backup.mariabackup/setup.py
- plugins/holland.backup.mongodump/setup.py
- plugins/holland.backup.mysql_lvm/setup.py
- plugins/holland.backup.mysqldump/setup.py
- plugins/holland.backup.pgdump/setup.py
- plugins/holland.backup.random/setup.py
- plugins/holland.backup.sqlite/setup.py
- plugins/holland.backup.tar/setup.py
- plugins/holland.backup.xtrabackup/setup.py
- plugins/holland.lib.common/holland/lib/compression.py
- plugins/holland.lib.common/setup.py
- plugins/holland.lib.lvm/setup.py
- plugins/holland.lib.mysql/setup.py
- setup.py
Fix holland.lib.common.compression options bug
> Fix holland.lib.common.compression options bug

- contrib/holland-commvault/holland_commvault/commvault.py
- holland/commands/mk_config.py
- holland/core/command/command.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/mysqldump/plugin.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/raw/plugin.py
- plugins/holland.lib.common/holland/lib/compression.py
- plugins/holland.lib.mysql/holland/lib/mysql/client/base.py
> Fix password encoding issue

- .pylintrc
- config/providers/pg_basebackup.conf
- plugins/ACTIVE
- plugins/README
- plugins/holland.backup.pg_basebackup/LICENSE
- plugins/holland.backup.pg_basebackup/README
- plugins/holland.backup.pg_basebackup/holland/__init__.py
- plugins/holland.backup.pg_basebackup/holland/backup/__init__.py
- plugins/holland.backup.pg_basebackup/holland/backup/pg_basebackup/__init__.py
- plugins/holland.backup.pg_basebackup/holland/backup/pg_basebackup/base.py
- plugins/holland.backup.pg_basebackup/holland/backup/pg_basebackup/interface.py
- plugins/holland.backup.pg_basebackup/setup.cfg
- plugins/holland.backup.pg_basebackup/setup.py
- plugins/holland.backup.pgdump/holland/backup/pgdump/base.py
Copy and modify the pg_dump plugin to use pg_basebackup.
> Add pg_basebackup plugin

- contrib/holland-commvault/setup.py
- plugins/holland.backup.example/setup.py
- plugins/holland.backup.mariabackup/setup.py
- plugins/holland.backup.mongodump/setup.py
- plugins/holland.backup.mysql_lvm/setup.py
- plugins/holland.backup.mysqldump/setup.py
- plugins/holland.backup.pg_basebackup/holland/backup/pg_basebackup/base.py
- plugins/holland.backup.pg_basebackup/holland/backup/pg_basebackup/interface.py
- plugins/holland.backup.pg_basebackup/setup.py
- plugins/holland.backup.pgdump/setup.py
- plugins/holland.backup.random/setup.py
- plugins/holland.backup.sqlite/setup.py
- plugins/holland.backup.tar/setup.py
- plugins/holland.backup.xtrabackup/setup.py
- plugins/holland.lib.common/holland/lib/util.py
- plugins/holland.lib.common/setup.py
- plugins/holland.lib.lvm/setup.py
- plugins/holland.lib.mysql/setup.py
- setup.py
Allow pg_basedump to expand backup_directory/backupdir
> Allow pg_basedump to expand backup_directory/backupdir

- holland/core/command/command.py
- plugins/holland.backup.mariabackup/holland/backup/mariabackup/util.py
- plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/actions/mysql/innodb.py
- plugins/holland.backup.xtrabackup/holland/backup/xtrabackup/util.py
> Innodb recovery.debug

- holland/core/command/command.py
> Kludge for argparse in Python 3.11

- holland/core/command/command.py
- plugins/holland.backup.mariabackup/holland/backup/mariabackup/util.py
- plugins/holland.backup.xtrabackup/holland/backup/xtrabackup/util.py
> Mbxb.version.byteliteral

- .pylintrc
- Jenkinsfile
- contrib/holland-commvault/holland_commvault/commvault.py
- holland/core/util/lock.py
- plugins/holland.lib.mysql/holland/lib/mysql/option/base.py
Fixes #371.
This just locks the pylint version to 2.17.x major release in Jenkins for now and includes fixes to support that version.
```
❯ pip list | grep pylint
pylint            2.17.7
❯ pylint holland
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
❯ for d in $(ls -d ./plugins/*/holland ./contrib/holland-commvault/holland_commvault); do echo $d; pylint $d; done
./contrib/holland-commvault/holland_commvault
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
./plugins/holland.backup.example/holland
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous …
```
> Pylint Fixes

- contrib/holland-commvault/setup.py
- plugins/holland.backup.example/setup.py
- plugins/holland.backup.mariabackup/setup.py
- plugins/holland.backup.mongodump/setup.py
- plugins/holland.backup.mysql_lvm/setup.py
- plugins/holland.backup.mysqldump/setup.py
- plugins/holland.backup.pg_basebackup/setup.py
- plugins/holland.backup.pgdump/setup.py
- plugins/holland.backup.random/setup.py
- plugins/holland.backup.sqlite/setup.py
- plugins/holland.backup.tar/setup.py
- plugins/holland.backup.xtrabackup/setup.py
- plugins/holland.lib.common/setup.py
- plugins/holland.lib.lvm/setup.py
- plugins/holland.lib.mysql/setup.py
- setup.py
Tags a holland 1.2.12 release.
@soulen3 - I may need some guidance on the packaging side of things once this is merged if you have any to share!
> Tag holland 1.2.12

- plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py
Fix spacing to address failing pylint test.
> Fix incorrect spacing to address pylint issue
